import React from 'react';
import { useTwin } from '../../context/TwinContext';
import {
  Sparkles,
  ChevronRight,
  ChevronLeft,
  X,
  Play,
  CheckCircle2,
  Sliders,
  CloudRain,
  MapPin,
  GitFork,
  Bot,
  Layers,
} from 'lucide-react';

export const DemoTourModal: React.FC = () => {
  const {
    isDemoTourOpen,
    setIsDemoTourOpen,
    demoTourStep,
    nextDemoStep,
    prevDemoStep,
    setDemoTourStep,
    playOperationalChime,
  } = useTwin();

  if (!isDemoTourOpen) return null;

  const tourSteps = [
    {
      step: 1,
      title: 'STEP 1: Open Command Center',
      tag: 'BASELINE STATE',
      desc: 'Observe the Mission Control Command Center under normal baseline operations. Notice the current weather (28°C, 10 mm/hr), traveler delay (+4 min), and overall operational risk rated as LOW / MODERATE.',
      actionText: 'Inspecting Command Center baseline',
      icon: Layers,
    },
    {
      step: 2,
      title: 'STEP 2: Open Weather Intelligence',
      tag: 'METEOROLOGICAL TELEMETRY',
      desc: 'Inspect real-time weather radar data, atmospheric indices (humidity, wind, barometric pressure), and the 3-hour precipitation timeline forecast.',
      actionText: 'Analyzing live weather stream',
      icon: CloudRain,
    },
    {
      step: 3,
      title: 'STEP 3: Open Digital Twin Map',
      tag: 'GEOSPATIAL TWIN',
      desc: 'Explore the 100,000-seat stadium precinct: Gates 1–8, Multi-level Parking P1–P3, Metro & Bus transit nodes, Grand Pavilion Hotel, and surrounding Ring Road arteries.',
      actionText: 'Viewing interactive precinct map',
      icon: MapPin,
    },
    {
      step: 4,
      title: 'STEP 4: What-If Weather Simulator',
      tag: 'SCENARIO CONFIGURATION',
      desc: 'We configure a weather event scenario: Rainfall is dialed up from 10 mm/hr to 60 mm/hr with wind gusts of 38 km/h and medium flooding severity.',
      actionText: 'Setting Rainfall to 60 mm/hr',
      icon: Sliders,
    },
    {
      step: 5,
      title: 'STEP 5: Execute Simulation Engine',
      tag: 'SANDBOX COMPUTATION',
      desc: 'Trigger the deterministic Cascade Propagation Engine. The engine executes deterministic transfer equations across all coupled sub-systems.',
      actionText: 'Simulation executed into Sandbox',
      icon: Play,
    },
    {
      step: 6,
      title: 'STEP 6: Cascade Impact Propagation',
      tag: 'DOMINO EFFECT',
      desc: 'Inspect the animated cascade chain: Rain (60 mm/hr) ➔ Traveler Delay (+18 min) ➔ Traffic Congestion (+27%) ➔ Parking Saturation (+21%) ➔ Gate Compression (+14%) ➔ Concourse Crowd (+9%) ➔ Transit Demand (+17%) ➔ Workforce Loss (-7%) ➔ HIGH RISK.',
      actionText: 'Tracing deterministic cascade chain',
      icon: GitFork,
    },
    {
      step: 7,
      title: 'STEP 7: Map Dynamic Visual Shift',
      tag: 'SPATIAL TELEMETRY',
      desc: 'Observe the geospatial map reflecting simulated stress: Gate 4 turns amber/red, P1 reaches 83% saturation, and approach roads show traffic congestion heatmaps.',
      actionText: 'Reviewing simulated map heatmap',
      icon: MapPin,
    },
    {
      step: 8,
      title: 'STEP 8: AI Operational Recommendations',
      tag: 'PRESCRIPTIVE ADVISORY',
      desc: 'Evaluate proactive recommendations generated by AI: Open P3 Overflow, Activate Shuttle Route B, Reassign Marshals to Gate 4, and broadcast Fan Advisories.',
      actionText: 'Reviewing AI mitigation actions',
      icon: Bot,
    },
    {
      step: 9,
      title: 'STEP 9: Probabilistic Confidence Intervals',
      tag: 'UNCERTAINTY QUANTIFICATION',
      desc: 'Review probabilistic confidence intervals for every prediction (e.g. Traffic: +27% expected with 84% confidence, range [+19% — +34%]).',
      actionText: 'Inspecting uncertainty bounds',
      icon: CheckCircle2,
    },
    {
      step: 10,
      title: 'STEP 10: Switch Back to LIVE WORLD',
      tag: 'ZERO LIVE CONTAMINATION',
      desc: 'Switch back to the LIVE WORLD baseline. Verify that the simulation sandbox ran completely isolated, leaving live stadium operations 100% unaltered.',
      actionText: 'Confirmed: Live world untouched',
      icon: Sparkles,
    },
  ];

  const current = tourSteps[demoTourStep - 1];
  const StepIcon = current.icon;

  return (
    <div className="fixed inset-0 z-50 bg-[#2B1710]/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-[#FFFEFB] border-2 border-[#2B1710] rounded-2xl max-w-2xl w-full p-6 shadow-floating relative overflow-hidden">
        {/* Top Header */}
        <div className="flex items-center justify-between gap-4 mb-4 pb-3 border-b border-[#E4DED3]">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-[#2B1710] text-[#FFFEFB] flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-[#EFE8DB]" />
            </div>
            <div>
              <h2 className="text-base font-black text-[#2B1710] font-display">
                GUIDED PRESENTATION WALKTHROUGH
              </h2>
              <span className="text-[11px] font-mono text-[#756D66]">
                Step {demoTourStep} of 10 — Weather-Driven Event Digital Twin
              </span>
            </div>
          </div>
          <button
            onClick={() => {
              playOperationalChime('click');
              setIsDemoTourOpen(false);
            }}
            className="p-1.5 rounded-lg text-[#756D66] hover:text-[#2B1710] hover:bg-[#EFE8DB] transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Progress Stepper Bar */}
        <div className="grid grid-cols-10 gap-1 mb-5">
          {tourSteps.map((s) => (
            <button
              key={s.step}
              onClick={() => {
                playOperationalChime('click');
                setDemoTourStep(s.step);
              }}
              className={`h-2 rounded-full transition-all ${
                s.step === demoTourStep
                  ? 'bg-[#2B1710] ring-2 ring-[#2B1710]/30'
                  : s.step < demoTourStep
                  ? 'bg-[#2F7D45]'
                  : 'bg-[#E4DED3]'
              }`}
              title={`Step ${s.step}: ${s.title}`}
            />
          ))}
        </div>

        {/* Current Step Content */}
        <div className="bg-[#F7F4ED] rounded-xl p-5 border border-[#E4DED3] mb-6">
          <div className="flex items-center justify-between gap-2 mb-2">
            <span className="text-[10px] font-mono font-black uppercase px-2.5 py-0.5 rounded bg-[#2B1710] text-[#FFFEFB]">
              {current.tag}
            </span>
            <div className="flex items-center gap-1.5 text-xs font-mono font-bold text-[#2F7D45]">
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span>LIVE AUTOMATION ACTIVE</span>
            </div>
          </div>

          <div className="flex items-start gap-3 my-3">
            <div className="p-3 rounded-xl bg-[#2B1710] text-[#FFFEFB] shrink-0">
              <StepIcon className="w-6 h-6 text-[#EFE8DB]" />
            </div>
            <div>
              <h3 className="text-lg font-black text-[#2A211D] mb-1 font-display">
                {current.title}
              </h3>
              <p className="text-xs text-[#756D66] leading-relaxed">
                {current.desc}
              </p>
            </div>
          </div>

          <div className="mt-3 pt-2.5 border-t border-[#E4DED3] flex items-center justify-between text-[11px] font-mono">
            <span className="text-[#756D66]">AUTO-NAV ACTION:</span>
            <span className="font-bold text-[#2B1710] bg-[#FFFEFB] px-2 py-0.5 rounded border border-[#E4DED3]">
              {current.actionText}
            </span>
          </div>
        </div>

        {/* Footer Navigation Buttons */}
        <div className="flex items-center justify-between gap-3">
          <button
            onClick={() => {
              playOperationalChime('click');
              prevDemoStep();
            }}
            disabled={demoTourStep === 1}
            className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-bold font-mono transition-all ${
              demoTourStep === 1
                ? 'opacity-40 cursor-not-allowed bg-[#EFE8DB] text-[#756D66]'
                : 'bg-[#EFE8DB] text-[#2B1710] hover:bg-[#E4DED3]'
            }`}
          >
            <ChevronLeft className="w-4 h-4" />
            <span>PREVIOUS STEP</span>
          </button>

          <span className="text-xs font-mono text-[#756D66] font-bold">
            {demoTourStep} / 10
          </span>

          <button
            onClick={() => {
              playOperationalChime('click');
              if (demoTourStep === 10) {
                setIsDemoTourOpen(false);
              } else {
                nextDemoStep();
              }
            }}
            className="flex items-center gap-1.5 px-5 py-2 rounded-lg bg-[#2B1710] text-[#FFFEFB] hover:bg-[#422820] text-xs font-bold font-mono shadow-subtle transition-all"
          >
            <span>{demoTourStep === 10 ? 'FINISH WALKTHROUGH' : 'NEXT STEP'}</span>
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
};
