import React from 'react';
import { useTwin } from '../../context/TwinContext';
import { StatusBadge } from '../common/StatusBadge';
import {
  Bot,
  Sparkles,
  CheckCircle2,
  Play,
  Clock,
  ArrowUpRight,
  ShieldCheck,
  AlertCircle,
  Car,
  SquareParking,
  DoorClosed,
  Train,
  Users,
} from 'lucide-react';
import { AiRecommendation } from '../../types';

export const AiRecommendations: React.FC = () => {
  const {
    recommendations,
    simulateRecommendation,
    applyRecommendation,
    playOperationalChime,
  } = useTwin();

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'PARKING':
        return SquareParking;
      case 'TRANSIT':
        return Train;
      case 'GATES':
        return DoorClosed;
      case 'WORKFORCE':
        return Users;
      default:
        return Sparkles;
    }
  };

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-3 pb-3 border-b border-[#E4DED3]">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-black text-[#2B1710] font-display">
              AI OPERATIONAL RECOMMENDATIONS & MITIGATION ENGINE
            </h2>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#2F7D45]/15 text-[#2F7D45] font-bold border border-[#2F7D45]/30">
              PRESCRIPTIVE ADVISORY
            </span>
          </div>
          <p className="text-xs text-[#756D66] font-mono">
            Proactive mitigation suggestions generated by the weather-coupled digital twin
          </p>
        </div>

        <div className="text-xs font-mono text-[#756D66] bg-[#FFFEFB] px-3.5 py-1.5 rounded-lg border border-[#E4DED3]">
          Advisories are suggestions only. Operational human override is maintained.
        </div>
      </div>

      {/* Recommendations Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {recommendations.map((rec) => {
          const CategoryIcon = getCategoryIcon(rec.category);
          const isApplied = rec.simulatedStatus === 'APPLIED';
          const isSimulated = rec.simulatedStatus === 'SIMULATED';

          return (
            <div
              key={rec.id}
              className={`glass-card rounded-2xl p-6 border transition-all duration-300 flex flex-col justify-between ${
                isApplied
                  ? 'border-[#2F7D45] bg-[#2F7D45]/5'
                  : isSimulated
                  ? 'border-[#6B46C1] bg-[#6B46C1]/5'
                  : 'border-[#E4DED3] hover:shadow-card hover:border-[#2B1710]/40'
              }`}
            >
              <div>
                {/* Header line: Category & Confidence */}
                <div className="flex items-center justify-between gap-2 mb-3 pb-2 border-b border-[#E4DED3]">
                  <div className="flex items-center gap-2">
                    <div className="p-1.5 rounded-lg bg-[#EFE8DB] text-[#2B1710]">
                      <CategoryIcon className="w-4 h-4" />
                    </div>
                    <span className="text-[11px] font-mono font-bold text-[#756D66] uppercase">
                      {rec.category}
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <span className="text-xs font-mono font-bold text-[#2F7D45] bg-[#2F7D45]/10 px-2 py-0.5 rounded">
                      Confidence: {rec.confidence}%
                    </span>
                  </div>
                </div>

                {/* Title */}
                <h3 className="text-base font-black text-[#2A211D] font-display mb-2">
                  {rec.title}
                </h3>

                {/* Reason */}
                <div className="bg-[#F7F4ED] p-3 rounded-xl border border-[#E4DED3] mb-3 text-xs font-mono">
                  <span className="text-[10px] text-[#756D66] font-bold block uppercase mb-0.5">
                    DIAGNOSTIC TRIGGER REASON:
                  </span>
                  <p className="text-[#2A211D] leading-relaxed font-sans">
                    {rec.reason}
                  </p>
                </div>

                {/* Projected Benefit */}
                <div className="bg-[#EFE8DB]/80 p-3 rounded-xl border border-[#E4DED3] mb-4 text-xs font-mono">
                  <span className="text-[10px] text-[#2B1710] font-bold block uppercase mb-0.5 flex items-center gap-1">
                    <Sparkles className="w-3 h-3" />
                    PROJECTED IMPACT BENEFIT:
                  </span>
                  <p className="text-[#2A211D] leading-relaxed font-sans font-medium">
                    {rec.projectedBenefit}
                  </p>
                </div>

                {/* Action Payload */}
                <div className="text-[11px] font-mono text-[#756D66] mb-4">
                  <span className="font-bold text-[#2A211D]">ACTION DISPATCH:</span>{' '}
                  {rec.actionPayload}
                </div>
              </div>

              {/* Action Buttons & Status */}
              <div className="pt-3 border-t border-[#E4DED3] flex items-center justify-between gap-2">
                <div className="text-[10px] font-mono text-[#756D66]">
                  Lead Time: <strong>{rec.estimatedLeadTime}</strong>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={() => {
                      simulateRecommendation(rec.id);
                    }}
                    disabled={isApplied || isSimulated}
                    className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all ${
                      isSimulated
                        ? 'bg-[#6B46C1] text-[#FFFEFB]'
                        : 'bg-[#EFE8DB] text-[#2B1710] hover:bg-[#E4DED3]'
                    }`}
                  >
                    {isSimulated ? 'SIMULATED' : 'SIMULATE'}
                  </button>

                  <button
                    onClick={() => {
                      applyRecommendation(rec.id);
                    }}
                    disabled={isApplied}
                    className={`px-3.5 py-1.5 rounded-lg text-xs font-mono font-bold transition-all flex items-center gap-1.5 ${
                      isApplied
                        ? 'bg-[#2F7D45] text-[#FFFEFB]'
                        : 'bg-[#2B1710] hover:bg-[#422820] text-[#FFFEFB] shadow-subtle'
                    }`}
                  >
                    {isApplied ? (
                      <>
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        <span>APPLIED</span>
                      </>
                    ) : (
                      <span>DISPATCH</span>
                    )}
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
